export const OrganisationActionTypes = {
    SET_ORGANISATIONS_START: ' SET_ORGANISATIONS_START',
    SET_ORGANISATIONS_SUCCESS: ' SET_ORGANISATIONS_SUCCESS',
    SET_ORGANISATIONS_FAILURE: ' SET_ORGANISATIONS_FAILURE'
};